/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\scene.gltf 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";
import * as THREE from "three";
import { motion } from "framer-motion-3d";
import { animate, useMotionValue } from "framer-motion";
import { useFrame } from "@react-three/fiber";

export function Office(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF("models/scene3.gltf");
  const texture = useTexture("textures/baked.jpg");
  texture.flipY = false;
  texture.encoding = THREE.sRGBEncoding;

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
  });
  const textureGlassMaterial = new THREE.MeshStandardMaterial({
    map: texture,
    transparent: true,
    opacity: 0.5,
  });

  return (
    <group {...props} dispose={null}>
      <group
        name="Chair"
        position={[14.392, 0.013, -10.46]}
        rotation={[Math.PI, -0.059, Math.PI]}
      >
        <mesh
          name="Node-Mesh007"
          geometry={nodes["Node-Mesh007"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh007_1"
          geometry={nodes["Node-Mesh007_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh007_2"
          geometry={nodes["Node-Mesh007_2"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh007_3"
          geometry={nodes["Node-Mesh007_3"].geometry}
          material={textureMaterial}
        />
      </group>
      <group
        name="ChamferBox017"
        position={[0.608, 0.953, -1.63]}
        rotation={[0, -0.628, 0]}
      >
        <mesh
          name="ChamferBox017_1"
          geometry={nodes.ChamferBox017_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="ChamferBox017_1_1"
          geometry={nodes.ChamferBox017_1_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="ChamferBox017_1_2"
          geometry={nodes.ChamferBox017_1_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="ChamferBox017_1_3"
          geometry={nodes.ChamferBox017_1_3.geometry}
          material={textureMaterial}
        />
      </group>
      <group
        name="Picture1"
        position={[-0.713, 2.24, -2.178]}
        rotation={[-Math.PI, 0.002, -Math.PI]}
      >
        <mesh
          name="Node-Mesh004"
          geometry={nodes["Node-Mesh004"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh004_1"
          geometry={nodes["Node-Mesh004_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh004_2"
          geometry={nodes["Node-Mesh004_2"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh004_3"
          geometry={nodes["Node-Mesh004_3"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh004_4"
          geometry={nodes["Node-Mesh004_4"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh004_5"
          geometry={nodes["Node-Mesh004_5"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh004_6"
          geometry={nodes["Node-Mesh004_6"].geometry}
          material={textureMaterial}
        />
      </group>
      <group
        name="Picture2"
        position={[0, 1.896, -2.168]}
        rotation={[-Math.PI, 0.031, -Math.PI]}
      >
        <mesh
          name="Wall_Art_Classical_Plane-Mesh"
          geometry={nodes["Wall_Art_Classical_Plane-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Wall_Art_Classical_Plane-Mesh_1"
          geometry={nodes["Wall_Art_Classical_Plane-Mesh_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Wall_Art_Classical_Plane-Mesh_2"
          geometry={nodes["Wall_Art_Classical_Plane-Mesh_2"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Wall_Art_Classical_Plane-Mesh_3"
          geometry={nodes["Wall_Art_Classical_Plane-Mesh_3"].geometry}
          material={textureMaterial}
        />
      </group>
      <group
        name="Picture3"
        position={[0.678, 2.259, -2.176]}
        rotation={[-Math.PI, 0.014, -Math.PI]}
      >
        <mesh
          name="Node-Mesh005"
          geometry={nodes["Node-Mesh005"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh005_1"
          geometry={nodes["Node-Mesh005_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh005_2"
          geometry={nodes["Node-Mesh005_2"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh005_3"
          geometry={nodes["Node-Mesh005_3"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh005_4"
          geometry={nodes["Node-Mesh005_4"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh005_5"
          geometry={nodes["Node-Mesh005_5"].geometry}
          material={textureMaterial}
        />
      </group>
      <group name="Plane" position={[0.708, 0, 0]}>
        <mesh
          name="Plane001"
          geometry={nodes.Plane001.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Plane001_1"
          geometry={nodes.Plane001_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Plane001_2"
          geometry={nodes.Plane001_2.geometry}
          material={textureGlassMaterial}
        />
        <mesh
          name="Plane001_3"
          geometry={nodes.Plane001_3.geometry}
          material={textureMaterial}
        />
      </group>
      <group
        name="plant"
        position={[1.741, 0, -1.541]}
        rotation={[-0.045, 1.082, -0.036]}
      >
        <mesh
          name="plant_01_Cube006-Mesh"
          geometry={nodes["plant_01_Cube006-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="plant_01_Cube006-Mesh_1"
          geometry={nodes["plant_01_Cube006-Mesh_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="plant_01_Cube006-Mesh_2"
          geometry={nodes["plant_01_Cube006-Mesh_2"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="plant_01_Cube006-Mesh_3"
          geometry={nodes["plant_01_Cube006-Mesh_3"].geometry}
          material={textureMaterial}
        />
      </group>
      <mesh
        name="Rug"
        geometry={nodes.Rug.geometry}
        material={textureMaterial}
        position={[-0.088, -0.031, 0.765]}
      />
      <group name="Desk" position={[0, 0, -1.603]} rotation={[0, -1.54, 0]}>
        <mesh
          name="Cube001_Cube002_BlackCoatSteel"
          geometry={nodes.Cube001_Cube002_BlackCoatSteel.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Cube001_Cube002_BlackCoatSteel_1"
          geometry={nodes.Cube001_Cube002_BlackCoatSteel_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Cube001_Cube002_BlackCoatSteel_2"
          geometry={nodes.Cube001_Cube002_BlackCoatSteel_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Cube001_Cube002_BlackCoatSteel_3"
          geometry={nodes.Cube001_Cube002_BlackCoatSteel_3.geometry}
          material={textureMaterial}
        />
        <mesh
          name="Cube001_Cube002_BlackCoatSteel_4"
          geometry={nodes.Cube001_Cube002_BlackCoatSteel_4.geometry}
          material={textureMaterial}
        />
      </group>
      <group name="Keyboard" position={[-0.108, 0.978, -1.355]} scale={0.298}>
        <mesh
          name="mesh34220672"
          geometry={nodes.mesh34220672.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh34220672_1"
          geometry={nodes.mesh34220672_1.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh34220672_2"
          geometry={nodes.mesh34220672_2.geometry}
          material={textureMaterial}
        />
        <mesh
          name="mesh34220672_3"
          geometry={nodes.mesh34220672_3.geometry}
          material={textureMaterial}
        />
      </group>
      <mesh
        name="Mouse"
        geometry={nodes.Mouse.geometry}
        material={textureMaterial}
        position={[0.413, 0.939, -1.27]}
        rotation={[0, 0.29, 0]}
        scale={0.003}
      />
      <group
        name="IMac"
        position={[0, 0.986, -1.854]}
        rotation={[3.074, 0.004, -Math.PI]}
        scale={0.043}
      >
        <mesh
          name="IMac_01_Cube026-Mesh"
          geometry={nodes["IMac_01_Cube026-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="IMac_01_Cube026-Mesh_1"
          geometry={nodes["IMac_01_Cube026-Mesh_1"].geometry}
          material={textureMaterial}
        />
      </group>
      <group name="LavaLamp" position={[-0.996, 1.062, -1.922]} scale={0.086}>
        <mesh
          name="Node-Mesh"
          geometry={nodes["Node-Mesh"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh_1"
          geometry={nodes["Node-Mesh_1"].geometry}
          material={textureMaterial}
        />
        <mesh
          name="Node-Mesh_2"
          geometry={nodes["Node-Mesh_2"].geometry}
          material={textureMaterial}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/scene3.gltf");
